### ISSUE TITLE
Accession uploading issue

### ISSUE THREAD

**Issue by sidevshiy** [solgenomics/breedbase_dockerfile#51]
Hello! 
I have breedbase installed in the docker container v0.98
I have issue while accession uploading process.

VM2252:1 Uncaught SyntaxError: Unexpected non-whitespace character after JSON at position 389 (line 1 column 390)
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.complete (Accessions.js:24:417)
    at HTMLIFrameElement.<anonymous> (iframe-post-form.js:26:18)
    at HTMLIFrameElement.dispatch (jquery.js:371:476)
    at elemData.handle (jquery.js:357:166)

When look into debug, json file looks the following way

{"full_data":{"WGR000TEST":{"organizationName":null,"germplasmName":"WGR000TEST","populationName":null,"species":"Abatia canescens","defaultDisplayName":"WGR000TEST","synonyms":[]}},"absent_organisms":[],"fuzzy_organisms":[],"absent":["WGR000TEST"],"found":[],"found_organisms":[{"matched_string":"Abatia canescens","unique_name":"Abatia canescens"}],"fuzzy":[],"success":"1","list_id":51}<.div class="json-formatter-container"></div>

that <.div class="json-formatter-container"></div> shows up there really wired way.

I can't figure out if it is a problem of the accession file itself or backend issue ? Probably I need to try to install newer version...
Have you met with this kind of issue in v0.98 ?

**Comment by sidevshiy** [comment]
I put "." after < sign because in other case it hides in the chat
